name: Feature request
description: Suggest an improvement
labels: ["enhancement"]
body:
  - type: textarea
    id: what
    attributes:
      label: What do you want to add/change?
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context / use-case
    validations:
      required: false

